<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
		<Version>4.0.0</Version>
		<Product>Engendro</Product>
		<Company>Indiesruption</Company>
		<Authors>Indiesruption</Authors>
		<Copyright>Copyright (C) 2020 Indiesruption</Copyright>
		<RootNamespace>Engendro</RootNamespace>
		<PackageId>Engendro.Engine</PackageId>
		<AssemblyName>Engendro</AssemblyName>
		<AnalysisLevel>latest</AnalysisLevel>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
		<EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
		<TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants)TRACE;WINDOWS</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>$(DefineConstants)TRACE;WINDOWS</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4" />
		<PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4" />
	</ItemGroup>
</Project>
