<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);QUICK_START</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4.1" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Adberration\Adberration.csproj" />
    <ProjectReference Include="..\Engendro\Engendro.csproj" />
  </ItemGroup>
</Project>